import type { FirmwareCase } from "../schema";

// Metadata transcribed from each linked research record; never firmware bytes.
export const amiCases = [
  {
    id: "intel-nuc10i5fnh-0067",
    label: "Intel NUC10i5FNH BIOS 0067",
    sha256: "12770cbddbab0fd071e91142afe6b1882c7a50c0e7b438866f6b99b5c660da64",
    size: 20971520,
    fileNames: ["FNCML357.0067.CAP", "FNCML357.0067(2).CAP"],
    brand: "Intel",
    source: "docs/ami/samples/intel-nuc10i5fnh-0067.md",
    structure: {
      family: "ami-aptio",
      firmwareVolumeCount: 19,
      ffs2VolumeCount: 19,
      ffs3VolumeCount: 0,
      outerSetupCount: 0,
      outerAmitseCount: 0,
      guidedLzmaSectionCount: 15,
      formSetCount: 1,
      container: "firmware-volume-image",
      layout: "unified-setup-formset",
      navigation: "single-formset-ifr-hub",
    },
    regressionTests: ["src/components/scripts/singleFormSetNavigation.test.ts"],
    limitations: [
      "FID is not a validated general generation discriminator; full-image writing is blocked.",
    ],
    generation: {
      generation: "aptio-v",
      confidence: "probable",
      conflict: false,
    },
  },
  {
    id: "asus-prime-z370-p-3004",
    label: "ASUS PRIME Z370-P 3004",
    sha256: "e862e5b0fdce10e44764be6072dd5b8017544264353dbfa02c8074e0ccc15190",
    size: 16779264,
    fileNames: ["PRIME-Z370-P-ASUS-3004.CAP"],
    brand: "ASUS",
    source: "docs/ami/single-formset-ifr-navigation.md",
    structure: {
      family: "ami-aptio",
      formSetCount: 1,
      formCount: 205,
      container: "vendor-image",
      layout: "unified-setup-formset",
      navigation: "single-formset-ifr-hub",
    },
    regressionTests: ["src/components/scripts/singleFormSetNavigation.test.ts"],
    limitations: [
      "HII Hide/Show round trip was verified; capsule output and compressed full-image writing remain blocked.",
    ],
  },
  {
    id: "asus-rog-strix-z390-e",
    label: "ASUS ROG STRIX Z390-E GAMING",
    sha256: "9344b904cd319b3d385ffdf74d232a5e3999a2963cc74937af95a631a87f1454",
    size: 16781312,
    fileNames: ["SZ390E.CAP"],
    brand: "ASUS",
    source: "docs/ami/single-formset-ifr-navigation.md",
    structure: {
      family: "ami-aptio",
      formSetCount: 1,
      formCount: 229,
      container: "vendor-image",
      layout: "unified-setup-formset",
      navigation: "single-formset-ifr-hub",
    },
    regressionTests: ["src/components/scripts/singleFormSetNavigation.test.ts"],
    limitations: [
      "AMITSE-only registrations do not establish tabs; capsule reconstruction remains out of scope.",
    ],
  },
  {
    id: "asus-k56cb-205",
    label: "ASUS K56CB 205",
    sha256: "ab56462aef141f05beea299aa14fc6fb6234412cf83f59903aef15807f2be1e9",
    size: 6293504,
    fileNames: ["K56CBAS.205"],
    brand: "ASUS",
    source: "docs/aptio-iv/samples/cross-vendor-intake.md",
    structure: {
      family: "ami-aptio",
      intelDescriptor: false,
      firmwareVolumeCount: 3,
      outerSetupCount: 1,
      outerAmitseCount: 1,
      container: "vendor-image",
    },
    regressionTests: ["src/components/scripts/aptioIvImage.test.ts"],
    limitations: ["Intake confirms outer structures, not safe reconstruction."],
    generation: {
      generation: "aptio-iv",
      confidence: "confirmed",
      conflict: false,
    },
  },
  {
    id: "asus-rampage-iv-extreme-4901",
    label: "ASUS Rampage IV Extreme 4901",
    sha256: "772c44e15c76315de3dc2f772360b643ddffe726ff6d1700d1a021cc0560aef5",
    size: 8390656,
    fileNames: ["Rampage IV Extreme 4901 CAP"],
    brand: "ASUS",
    source: "docs/aptio-iv/samples/cross-vendor-intake.md",
    structure: {
      family: "ami-aptio",
      firmwareVolumeCount: 7,
      outerSetupCount: 1,
      outerAmitseCount: 1,
      container: "vendor-image",
    },
    regressionTests: ["src/components/scripts/aptioIvImage.test.ts"],
    limitations: [
      "Vendor header retained in input identity; capsule output is out of scope.",
    ],
    generation: {
      generation: "aptio-iv",
      confidence: "confirmed",
      conflict: false,
    },
  },
  {
    id: "asus-sabertooth-z97-mark1-2702",
    label: "ASUS Sabertooth Z97 Mark 1 2702",
    sha256: "cb71e90c3863a3d0c097d5774bf5dd536bf4f528f679e17d27c2d1add69c6462",
    size: 8390656,
    fileNames: ["Sabertooth Z97 Mark 1 2702 CAP"],
    brand: "ASUS",
    source: "docs/aptio-iv/samples/cross-vendor-intake.md",
    structure: {
      family: "ami-aptio",
      firmwareVolumeCount: 6,
      outerSetupCount: 1,
      outerAmitseCount: 1,
      container: "vendor-image",
    },
    regressionTests: ["src/components/scripts/aptioIvImage.test.ts"],
    limitations: [
      "Vendor header retained in input identity; capsule output is out of scope.",
    ],
    generation: {
      generation: "aptio-iv",
      confidence: "confirmed",
      conflict: false,
    },
  },
  {
    id: "hp-server-l01-0278",
    label: "HP Server L01 02.78",
    sha256: "c13e4495042f0bda3deadf4d110bf241cdeb6679153cde001b24e7e337b4e2c1",
    size: 16777216,
    fileNames: ["L01_0278.BIN"],
    brand: "HP",
    source: "docs/aptio-iv/samples/hp-server-l01-0278.md",
    structure: {
      family: "ami-aptio",
      intelDescriptor: true,
      firmwareVolumeCount: 5,
      ffs2VolumeCount: 5,
      ffs3VolumeCount: 0,
      formSetCount: 11,
      formCount: 145,
      container: "intel-flash",
      layout: "split-form-packages",
    },
    regressionTests: [
      "src/components/scripts/aptioIvImage.test.ts",
      "src/components/scripts/setupData.test.ts",
    ],
    limitations: [
      "287 controls have ambiguous or missing SetupData matches; historical external-tool analysis does not prove current browser write support.",
    ],
    generation: {
      generation: "aptio-iv",
      confidence: "confirmed",
      conflict: false,
    },
  },
  {
    id: "hp-ipisb-ch2-w25q32",
    label: "HP IPISB-CH2 W25Q32",
    sha256: "6d18c962f3ffa6b941ada4e6fa71be4cdf1e7ff8297f5f4a4b73e29969f350a9",
    size: 4194304,
    fileNames: ["IPISB-CH2-W25Q32_20170616_155538.BIN"],
    brand: "HP",
    source: "docs/aptio-iv/samples/hp-ipisb-ch2-w25q32.md",
    structure: {
      family: "ami-aptio",
      intelDescriptor: true,
      firmwareVolumeCount: 4,
      formSetCount: 11,
      formCount: 78,
      container: "intel-flash",
      layout: "split-form-packages",
    },
    regressionTests: [
      "src/components/scripts/aptioIvImage.test.ts",
      "src/components/scripts/setupData.test.ts",
    ],
    limitations: [
      "196 CheckBox matches are ambiguous and one is missing; full-image writing needs independent acceptance.",
    ],
    generation: {
      generation: "aptio-iv",
      confidence: "confirmed",
      conflict: false,
    },
  },
  {
    id: "hp-boa-8005",
    label: "HP BOA BIOS 80.05",
    sha256: "c0a18c739897fcc0ee428802272c566ec49014b6074aadf0c55fdb5513e816ff",
    size: 8388608,
    fileNames: ["BOA_8005.BIN"],
    brand: "HP",
    source: "docs/aptio-iv/samples/hp-boa-8005.md",
    structure: {
      family: "ami-aptio",
      intelDescriptor: false,
      firmwareVolumeCount: 5,
      ffs2VolumeCount: 5,
      ffs3VolumeCount: 0,
      outerSetupCount: 0,
      outerAmitseCount: 0,
      formSetCount: 11,
      formCount: 103,
      container: "firmware-volume-image",
      layout: "split-form-packages",
    },
    regressionTests: [
      "src/components/scripts/aptioIvImage.test.ts",
      "src/components/scripts/aptioIvExtractor.test.ts",
    ],
    limitations: [
      "Nested compression is required; 113 SetupData controls remain ambiguous or unmatched.",
    ],
    generation: {
      generation: "aptio-iv",
      confidence: "confirmed",
      conflict: false,
    },
  },
  {
    id: "msi-e7752ims-2b0",
    label: "MSI E7752IMS 2.B0",
    sha256: "49593660b086ae48a3c968286e68c4b8e7e13e934483776b13802f3de4e3b330",
    size: 8388608,
    fileNames: ["E7752IMS.2B0"],
    brand: "MSI",
    source: "docs/aptio-iv/samples/cross-vendor-intake.md",
    structure: {
      family: "ami-aptio",
      intelDescriptor: true,
      firmwareVolumeCount: 3,
      outerSetupCount: 1,
      outerAmitseCount: 1,
      container: "intel-flash",
    },
    regressionTests: ["src/components/scripts/aptioIvImage.test.ts"],
    limitations: [
      "Initial structural intake does not establish editing or write readiness.",
    ],
    generation: {
      generation: "aptio-iv",
      confidence: "confirmed",
      conflict: false,
    },
  },
  {
    id: "msi-e7893ams-140",
    label: "MSI E7893AMS 1.40",
    sha256: "cebd6ec82bdd73b3dd953f981cd084efb789f52bc2481a9bfd242b5693b5e6ba",
    size: 8388608,
    fileNames: ["E7893AMS.140"],
    brand: "MSI",
    source: "docs/aptio-iv/samples/cross-vendor-intake.md",
    structure: {
      family: "ami-aptio",
      intelDescriptor: false,
      firmwareVolumeCount: 3,
      outerSetupCount: 1,
      outerAmitseCount: 1,
      container: "vendor-image",
    },
    regressionTests: ["src/components/scripts/aptioIvImage.test.ts"],
    limitations: [
      "Initial structural intake does not establish editing or write readiness.",
    ],
    generation: {
      generation: "aptio-iv",
      confidence: "confirmed",
      conflict: false,
    },
  },
  {
    id: "asrock-z77-extreme4-300",
    label: "ASRock Z77 Extreme4 3.00",
    sha256: "3bddf9d2f6d86e8102be4bb2cd54c49876349859c0d50a7cb7aaa7eec6870761",
    size: 8388608,
    fileNames: ["Z77EXT43.00"],
    brand: "ASRock",
    source: "docs/aptio-iv/samples/cross-vendor-intake.md",
    structure: {
      intelDescriptor: true,
      firmwareVolumeCount: 4,
      outerSetupCount: 0,
      outerAmitseCount: 0,
      container: "intel-flash",
    },
    regressionTests: ["src/components/scripts/aptioIvImage.test.ts"],
    limitations: [
      "Aptio IV was only a candidate at intake; Setup/AMITSE require recursive decompression.",
    ],
  },
  {
    id: "supermicro-x9dr3-if-34",
    label: "Supermicro X9DR3/i-F 3.4",
    sha256: "3b4f01b4fb3361bf0ed8fe290225303172a72bb3ce479e83ca28c0bcff5d5b9c",
    size: 16777216,
    fileNames: ["X9DRi0.630"],
    brand: "Supermicro",
    source: "docs/aptio-iv/samples/supermicro-x9dr3-if-34.md",
    structure: {
      family: "ami-aptio",
      intelDescriptor: true,
      firmwareVolumeCount: 3,
      outerSetupCount: 1,
      outerAmitseCount: 1,
      container: "intel-flash",
    },
    regressionTests: [
      "src/components/scripts/aptioIvImage.test.ts",
      "src/components/scripts/aptioIvExtractor.test.ts",
    ],
    limitations: [
      "Standard/Tiano compression is documented; complete parsed HII statistics and write acceptance are not established by this record.",
    ],
    generation: {
      generation: "aptio-iv",
      confidence: "confirmed",
      conflict: false,
    },
  },
  {
    id: "ami-image2-nested-lzma",
    label: "AMI image2.bin nested LZMA regression",
    sha256: "56430f2f4f9aef4e50f503dc8397fdb20b005bf38a8b9029c43e3eed56c39229",
    size: 33554432,
    fileNames: ["image2.bin", "image3.bin"],
    source: "docs/ami/sample-corpus.md",
    structure: {
      family: "ami-aptio",
      container: "intel-flash",
      intelDescriptor: true,
      firmwareVolumeCount: 12,
      ffs2VolumeCount: 12,
      ffs3VolumeCount: 0,
      outerSetupCount: 0,
      guidedLzmaSectionCount: 8,
    },
    regressionTests: ["src/components/scripts/aptioIvExtractor.test.ts"],
    limitations: [
      "image3.bin is byte-identical, not a separate case.",
      "Shared IV/V structures do not confirm generation; compressed full-image output remains blocked.",
    ],
  },
] as const satisfies readonly FirmwareCase[];
